### GET
GET http://localhost:8080/students

### GET BY ID
GET http://localhost:8080/students/1

### POST
POST http://localhost:8080/students
Content-Type: application/json

{
  "Name": "Lucas121",
  "CPF": 12345,
  "Email": "lucas@test.com1",
  "Age": 24,
  "Active": true
}

### PUT
PUT http://localhost:8080/users/1
Content-Type: application/json

{
  "name": "Lucas Atualizado"
}

### DELETE
DELETE http://localhost:8080/users/1
